/* import { createContext } from "react";

export const CardContext= createContext()

 */

export const cardstate=[
   {
      cardhead:"card head",
      carddescription:" Card description is written here",
      cardcost:"MYR 3000",
      cardcolor1:"white",
      cardcolor2:"red",
      cardcolor3:"gray",
      gender:"female",
      featured:true,
      no_of_purchase:43,
      rate:6,
      cardverified:false,
      topchoice:true,
      cardimage:'/images/female.jpg',
      _id:"53"
   },
    {
        cardhead:"card head",
        carddescription:" Card description is written here",
        cardcost:"MYR 3000",
        cardcolor1:"white",
        cardcolor2:"red",
        cardcolor3:"gray",
        cardverified:true,
        gender:"male",
        featured:true,
        no_of_purchase:22,
        rate:4,
        topchoice:false,
        cardimage:'/images/male.jpg',
        _id:"1"
     },
     {
        cardhead:"card head",
        carddescription:" Card description is written here",
        cardcost:"MYR 3000",
        cardcolor1:"black",
        cardcolor2:"red",
        cardcolor3:"gray",
        gender:"male",
        featured:false,
        no_of_purchase:22,
        rate:4,
        cardverified:true,
        topchoice:true,
        cardimage:'/images/a.jpg',
        _id:"2"
     },
     {
        cardhead:"card head",
        carddescription:" Card description is written here",
        cardcost:"MYR 3000",
        cardcolor1:"black",
        cardcolor2:"red",
        cardcolor3:"gray",
        gender:"male",
        featured:false,
        no_of_purchase:22,
        rate:4,
        cardverified:true,
        topchoice:true,
        cardimage:'/images/b.jpg',
        _id:"2e"
     },
     {
        cardhead:"card head",
        carddescription:" Card description is written here",
        cardcost:"MYR 3000",
        cardcolor1:"black",
        cardcolor2:"red",
        cardcolor3:"gray",
        gender:"male",
        featured:false,
        no_of_purchase:22,
        rate:4,
        cardverified:true,
        topchoice:true,
        cardimage:'/images/c.jpg',
        _id:"2x"
     },
     {
        cardhead:"card head",
        carddescription:" Card description is written here",
        cardcost:"MYR 3000",
        cardcolor1:"white",
        cardcolor2:"red",
        cardcolor3:"gray",
        gender:"female",
        featured:true,
        no_of_purchase:22,
        rate:4,
        cardverified:"",
        topchoice:true,
        cardimage:'/images/f.jpg',
        _id:"3"
     },
     {
        cardhead:"card head",
        carddescription:" Card description is written here",
        cardcost:"MYR 3000",
        cardcolor1:"white",
        cardcolor2:"red",
        cardcolor3:"gray",
        gender:"female",
        featured:true,
        no_of_purchase:22,
        rate:4,
        cardverified:true,
        topchoice:true,
        cardimage:'/images/d.jpg',
        _id:"4"
     },
     {
        cardhead:"card head",
        carddescription:" Card description is written here",
        cardcost:"MYR 3000",
        cardcolor1:"white",
        cardcolor2:"red",
        cardcolor3:"gray",
        gender:"female",
        featured:true,
        no_of_purchase:43,
        rate:6,
        cardverified:false,
        topchoice:true,
        cardimage:'/images/e.jpg',
        _id:"5"
     },
     {
        cardhead:"card head",
        carddescription:" Card description is written here",
        cardcost:"MYR 3000",
        cardcolor1:"white",
        cardcolor2:"red",
        cardcolor3:"gray",
        gender:"female",
        featured:true,
        no_of_purchase:43,
        rate:6,
        cardverified:false,
        topchoice:true,
        cardimage:'/images/h.png',
        _id:"5e"
     },
     {
        cardhead:"card head",
        carddescription:" Card description is written here",
        cardcost:"MYR 3000",
        cardcolor1:"white",
        cardcolor2:"red",
        cardcolor3:"gray",
        gender:"female",
        featured:true,
        no_of_purchase:43,
        rate:6,
        cardverified:false,
        topchoice:true,
        cardimage:'/images/g.png',
        _id:"5g"
     },
    
     
]
